### ISSUE TITLE
getText on MutableTextRange returns incorrect results when multiple lines are involved

### ISSUE THREAD

**Issue by CyriacBr** [mcchatman8009/text-manipulation#1]
Hi! For a project I have to manipulate text ranges, and as you said in the README it can be really tricky. So I looked for something on npm that'd make my life easier. Stumbled across you lib but noticed this bug:

When a MutableTextRange is composed of multiple lines, `getText` behaves incorrectly. Here's a quick reproduction:
```js
      const t = require('text-manipulation');
      const buffer = t.createBuffer('line1\nline2\nline3');
      const range = new t.MutableTextRange(
        [
          { column: 1, line: 1 },
          { column: 5, line: 2 },
        ],
        buffer
      );
      console.log('range.getText() :>> ', range.getText());
      // expected: ine2\nline3
      // actual: ine2\nine3
```

**Comment by mcchatman8009** [comment]
This issue has been fixed. Thanks @CyriacBr  for reporting!
